name: Update Hash

# Run on manual triggers, PRs, and daily at UTC noon
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # runs at 12:00 UTC daily :contentReference[oaicite:1]{index=1}

jobs:
  update-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Fetch latest FireAlpaca AppImage hash
        id: fetch_hash
        run: |
          HASH=$(nix-prefetch-url https://firealpaca.com/download/linux)
          echo "HASH=$HASH" >> $GITHUB_ENV

      - name: Convert to SRI format
        id: sri
        run: |
          SRI=$(nix hash to-sri --type sha256 "$HASH")
          echo "SRI=$SRI" >> $GITHUB_ENV

      - name: Update Nix expression with new hash
        run: |
          sed -i 's|hash = "sha256-[^"]*";|hash = "'"$SRI"'";|' firealpaca.nix

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add firealpaca.nix
          git commit -m "Update FireAlpaca AppImage hash"
          git push
